// Generated by gencpp from file pandaset_viewer/LidarPoint.msg
// DO NOT EDIT!


#ifndef PANDASET_VIEWER_MESSAGE_LIDARPOINT_H
#define PANDASET_VIEWER_MESSAGE_LIDARPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pandaset_viewer
{
template <class ContainerAllocator>
struct LidarPoint_
{
  typedef LidarPoint_<ContainerAllocator> Type;

  LidarPoint_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , i(0.0)
    , semseg(0)  {
    }
  LidarPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , i(0.0)
    , semseg(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _i_type;
  _i_type i;

   typedef int64_t _semseg_type;
  _semseg_type semseg;





  typedef boost::shared_ptr< ::pandaset_viewer::LidarPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pandaset_viewer::LidarPoint_<ContainerAllocator> const> ConstPtr;

}; // struct LidarPoint_

typedef ::pandaset_viewer::LidarPoint_<std::allocator<void> > LidarPoint;

typedef boost::shared_ptr< ::pandaset_viewer::LidarPoint > LidarPointPtr;
typedef boost::shared_ptr< ::pandaset_viewer::LidarPoint const> LidarPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pandaset_viewer::LidarPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pandaset_viewer::LidarPoint_<ContainerAllocator1> & lhs, const ::pandaset_viewer::LidarPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.i == rhs.i &&
    lhs.semseg == rhs.semseg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pandaset_viewer::LidarPoint_<ContainerAllocator1> & lhs, const ::pandaset_viewer::LidarPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pandaset_viewer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pandaset_viewer::LidarPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pandaset_viewer::LidarPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pandaset_viewer::LidarPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fc9d8d88b9e8c37f2570312bc537312";
  }

  static const char* value(const ::pandaset_viewer::LidarPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fc9d8d88b9e8c37ULL;
  static const uint64_t static_value2 = 0xf2570312bc537312ULL;
};

template<class ContainerAllocator>
struct DataType< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pandaset_viewer/LidarPoint";
  }

  static const char* value(const ::pandaset_viewer::LidarPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 i\n"
"int64 semseg\n"
;
  }

  static const char* value(const ::pandaset_viewer::LidarPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.i);
      stream.next(m.semseg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pandaset_viewer::LidarPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pandaset_viewer::LidarPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "semseg: ";
    Printer<int64_t>::stream(s, indent + "  ", v.semseg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDASET_VIEWER_MESSAGE_LIDARPOINT_H
